# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SkripsiSKW' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SkripsiSKW
 pod 'Firebase/Auth'
 pod 'Firebase/Storage'
 pod 'Firebase/Firestore'
 pod 'FirebaseFirestoreSwift', '8.1.0-beta'
 pod 'SDWebImageSwiftUI'

  target 'SkripsiSKWTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SkripsiSKWUITests' do
    # Pods for testing
  end

end
